# Run following command to run a MS SQL Server 2022 instance in docker container
# docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=admin@123" -p 1433:1433 --name sql1 --hostname sql1 -d mcr.microsoft.com/mssql/server:2022-latest

# Following is docker compose file content to create a docker swamp stack deployment
# Run command `docker stack deploy -c docker-compose.yml mssql`

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "admin@123"
      ACCEPT_EULA:  "Y"
    ports:
      - 1433:1433    
    hostname: "mssql"
    volumes:
      - mssql-data:/var/opt/mssql    

volumes:
  mssql-data:
